// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: alternativas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlternativa = `-- name: CreateAlternativa :one
INSERT INTO alternativas (question_id, texto_alternativa, correta)
VALUES ($1, $2, $3)
RETURNING id, question_id, texto_alternativa, correta
`

type CreateAlternativaParams struct {
	QuestionID       pgtype.UUID `json:"question_id"`
	TextoAlternativa string      `json:"texto_alternativa"`
	Correta          pgtype.Bool `json:"correta"`
}

func (q *Queries) CreateAlternativa(ctx context.Context, arg CreateAlternativaParams) (Alternativa, error) {
	row := q.db.QueryRow(ctx, createAlternativa, arg.QuestionID, arg.TextoAlternativa, arg.Correta)
	var i Alternativa
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.TextoAlternativa,
		&i.Correta,
	)
	return i, err
}

const deleteAlternativa = `-- name: DeleteAlternativa :exec
DELETE FROM alternativas
WHERE id = $1
`

func (q *Queries) DeleteAlternativa(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlternativa, id)
	return err
}

const getAlternativa = `-- name: GetAlternativa :one
SELECT id, question_id, texto_alternativa, correta
FROM alternativas
WHERE id = $1
`

func (q *Queries) GetAlternativa(ctx context.Context, id pgtype.UUID) (Alternativa, error) {
	row := q.db.QueryRow(ctx, getAlternativa, id)
	var i Alternativa
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.TextoAlternativa,
		&i.Correta,
	)
	return i, err
}

const listAlternativasByQuestion = `-- name: ListAlternativasByQuestion :many
SELECT id, question_id, texto_alternativa, correta
FROM alternativas
WHERE question_id = $1
ORDER BY id
`

func (q *Queries) ListAlternativasByQuestion(ctx context.Context, questionID pgtype.UUID) ([]Alternativa, error) {
	rows, err := q.db.Query(ctx, listAlternativasByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alternativa{}
	for rows.Next() {
		var i Alternativa
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.TextoAlternativa,
			&i.Correta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlternativa = `-- name: UpdateAlternativa :one
UPDATE alternativas
SET
    texto_alternativa = $2,
    correta = $3
WHERE id = $1
RETURNING id, question_id, texto_alternativa, correta
`

type UpdateAlternativaParams struct {
	ID               pgtype.UUID `json:"id"`
	TextoAlternativa string      `json:"texto_alternativa"`
	Correta          pgtype.Bool `json:"correta"`
}

func (q *Queries) UpdateAlternativa(ctx context.Context, arg UpdateAlternativaParams) (Alternativa, error) {
	row := q.db.QueryRow(ctx, updateAlternativa, arg.ID, arg.TextoAlternativa, arg.Correta)
	var i Alternativa
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.TextoAlternativa,
		&i.Correta,
	)
	return i, err
}
