// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assuntos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssunto = `-- name: CreateAssunto :one
INSERT INTO assuntos (disciplina_id, nome)
VALUES ($1, $2)
RETURNING id, disciplina_id, nome
`

type CreateAssuntoParams struct {
	DisciplinaID pgtype.UUID `json:"disciplina_id"`
	Nome         string      `json:"nome"`
}

func (q *Queries) CreateAssunto(ctx context.Context, arg CreateAssuntoParams) (Assunto, error) {
	row := q.db.QueryRow(ctx, createAssunto, arg.DisciplinaID, arg.Nome)
	var i Assunto
	err := row.Scan(&i.ID, &i.DisciplinaID, &i.Nome)
	return i, err
}

const deleteAssunto = `-- name: DeleteAssunto :exec
DELETE FROM assuntos
WHERE id = $1
`

func (q *Queries) DeleteAssunto(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssunto, id)
	return err
}

const getAssunto = `-- name: GetAssunto :one
SELECT id, disciplina_id, nome
FROM assuntos
WHERE id = $1
`

func (q *Queries) GetAssunto(ctx context.Context, id pgtype.UUID) (Assunto, error) {
	row := q.db.QueryRow(ctx, getAssunto, id)
	var i Assunto
	err := row.Scan(&i.ID, &i.DisciplinaID, &i.Nome)
	return i, err
}

const listAssuntos = `-- name: ListAssuntos :many
SELECT id, disciplina_id, nome
FROM assuntos
ORDER BY nome
`

func (q *Queries) ListAssuntos(ctx context.Context) ([]Assunto, error) {
	rows, err := q.db.Query(ctx, listAssuntos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assunto{}
	for rows.Next() {
		var i Assunto
		if err := rows.Scan(&i.ID, &i.DisciplinaID, &i.Nome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssuntosByDisciplina = `-- name: ListAssuntosByDisciplina :many
SELECT id, disciplina_id, nome
FROM assuntos
WHERE disciplina_id = $1
ORDER BY nome
`

func (q *Queries) ListAssuntosByDisciplina(ctx context.Context, disciplinaID pgtype.UUID) ([]Assunto, error) {
	rows, err := q.db.Query(ctx, listAssuntosByDisciplina, disciplinaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assunto{}
	for rows.Next() {
		var i Assunto
		if err := rows.Scan(&i.ID, &i.DisciplinaID, &i.Nome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssunto = `-- name: UpdateAssunto :one
UPDATE assuntos
SET
    disciplina_id = $2,
    nome = $3
WHERE id = $1
RETURNING id, disciplina_id, nome
`

type UpdateAssuntoParams struct {
	ID           pgtype.UUID `json:"id"`
	DisciplinaID pgtype.UUID `json:"disciplina_id"`
	Nome         string      `json:"nome"`
}

func (q *Queries) UpdateAssunto(ctx context.Context, arg UpdateAssuntoParams) (Assunto, error) {
	row := q.db.QueryRow(ctx, updateAssunto, arg.ID, arg.DisciplinaID, arg.Nome)
	var i Assunto
	err := row.Scan(&i.ID, &i.DisciplinaID, &i.Nome)
	return i, err
}
