// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: choices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChoice = `-- name: CreateChoice :one
INSERT INTO
    choices (
        question_id,
        choice_text,
        is_correct
    )
VALUES ($1, $2, $3) RETURNING id, question_id, choice_text, is_correct
`

type CreateChoiceParams struct {
	QuestionID pgtype.UUID `json:"question_id"`
	ChoiceText string      `json:"choice_text"`
	IsCorrect  pgtype.Bool `json:"is_correct"`
}

func (q *Queries) CreateChoice(ctx context.Context, arg CreateChoiceParams) (Choice, error) {
	row := q.db.QueryRow(ctx, createChoice, arg.QuestionID, arg.ChoiceText, arg.IsCorrect)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ChoiceText,
		&i.IsCorrect,
	)
	return i, err
}

const deleteChoice = `-- name: DeleteChoice :exec
DELETE FROM choices WHERE id = $1
`

func (q *Queries) DeleteChoice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChoice, id)
	return err
}

const getChoice = `-- name: GetChoice :one
SELECT id, question_id, choice_text, is_correct FROM choices WHERE id = $1
`

func (q *Queries) GetChoice(ctx context.Context, id pgtype.UUID) (Choice, error) {
	row := q.db.QueryRow(ctx, getChoice, id)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ChoiceText,
		&i.IsCorrect,
	)
	return i, err
}

const listChoicesByQuestion = `-- name: ListChoicesByQuestion :many
SELECT id, question_id, choice_text, is_correct FROM choices WHERE question_id = $1 ORDER BY id
`

func (q *Queries) ListChoicesByQuestion(ctx context.Context, questionID pgtype.UUID) ([]Choice, error) {
	rows, err := q.db.Query(ctx, listChoicesByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Choice{}
	for rows.Next() {
		var i Choice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.ChoiceText,
			&i.IsCorrect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChoice = `-- name: UpdateChoice :one
UPDATE choices
SET
    choice_text = $2,
    is_correct = $3
WHERE
    id = $1 RETURNING id, question_id, choice_text, is_correct
`

type UpdateChoiceParams struct {
	ID         pgtype.UUID `json:"id"`
	ChoiceText string      `json:"choice_text"`
	IsCorrect  pgtype.Bool `json:"is_correct"`
}

func (q *Queries) UpdateChoice(ctx context.Context, arg UpdateChoiceParams) (Choice, error) {
	row := q.db.QueryRow(ctx, updateChoice, arg.ID, arg.ChoiceText, arg.IsCorrect)
	var i Choice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ChoiceText,
		&i.IsCorrect,
	)
	return i, err
}
