// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: disciplinas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDisciplina = `-- name: CreateDisciplina :one
INSERT INTO disciplinas (nome)
VALUES ($1)
RETURNING id, nome
`

func (q *Queries) CreateDisciplina(ctx context.Context, nome string) (Disciplina, error) {
	row := q.db.QueryRow(ctx, createDisciplina, nome)
	var i Disciplina
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}

const deleteDisciplina = `-- name: DeleteDisciplina :exec
DELETE FROM disciplinas
WHERE id = $1
`

func (q *Queries) DeleteDisciplina(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDisciplina, id)
	return err
}

const getDisciplina = `-- name: GetDisciplina :one
SELECT id, nome
FROM disciplinas
WHERE id = $1
`

func (q *Queries) GetDisciplina(ctx context.Context, id pgtype.UUID) (Disciplina, error) {
	row := q.db.QueryRow(ctx, getDisciplina, id)
	var i Disciplina
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}

const listDisciplinas = `-- name: ListDisciplinas :many
SELECT id, nome
FROM disciplinas
ORDER BY nome
`

func (q *Queries) ListDisciplinas(ctx context.Context) ([]Disciplina, error) {
	rows, err := q.db.Query(ctx, listDisciplinas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Disciplina{}
	for rows.Next() {
		var i Disciplina
		if err := rows.Scan(&i.ID, &i.Nome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDisciplina = `-- name: UpdateDisciplina :one
UPDATE disciplinas
SET nome = $2
WHERE id = $1
RETURNING id, nome
`

type UpdateDisciplinaParams struct {
	ID   pgtype.UUID `json:"id"`
	Nome string      `json:"nome"`
}

func (q *Queries) UpdateDisciplina(ctx context.Context, arg UpdateDisciplinaParams) (Disciplina, error) {
	row := q.db.QueryRow(ctx, updateDisciplina, arg.ID, arg.Nome)
	var i Disciplina
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}
