// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Choice struct {
	ID         pgtype.UUID `json:"id"`
	QuestionID pgtype.UUID `json:"question_id"`
	ChoiceText string      `json:"choice_text"`
	IsCorrect  pgtype.Bool `json:"is_correct"`
}

type Question struct {
	ID           pgtype.UUID        `json:"id"`
	Statement    string             `json:"statement"`
	Year         int32              `json:"year"`
	TopicID      pgtype.UUID        `json:"topic_id"`
	Position     pgtype.Text        `json:"position"`
	Level        pgtype.Text        `json:"level"`
	Difficulty   pgtype.Text        `json:"difficulty"`
	Modality     pgtype.Text        `json:"modality"`
	PracticeArea pgtype.Text        `json:"practice_area"`
	FieldOfStudy pgtype.Text        `json:"field_of_study"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Subject struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type Topic struct {
	ID        pgtype.UUID `json:"id"`
	SubjectID pgtype.UUID `json:"subject_id"`
	Name      string      `json:"name"`
}
