// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alternativa struct {
	ID               pgtype.UUID `json:"id"`
	QuestionID       pgtype.UUID `json:"question_id"`
	TextoAlternativa string      `json:"texto_alternativa"`
	Correta          pgtype.Bool `json:"correta"`
}

type Assunto struct {
	ID           pgtype.UUID `json:"id"`
	DisciplinaID pgtype.UUID `json:"disciplina_id"`
	Nome         string      `json:"nome"`
}

type Disciplina struct {
	ID   pgtype.UUID `json:"id"`
	Nome string      `json:"nome"`
}

type Question struct {
	ID           pgtype.UUID        `json:"id"`
	Enunciado    string             `json:"enunciado"`
	Ano          int32              `json:"ano"`
	AssuntoID    pgtype.UUID        `json:"assunto_id"`
	Instituicao  pgtype.Text        `json:"instituicao"`
	Cargo        pgtype.Text        `json:"cargo"`
	Nivel        pgtype.Text        `json:"nivel"`
	Dificuldade  pgtype.Text        `json:"dificuldade"`
	Modalidade   pgtype.Text        `json:"modalidade"`
	AreaAtuacao  pgtype.Text        `json:"area_atuacao"`
	AreaFormacao pgtype.Text        `json:"area_formacao"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
