// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountQuestions(ctx context.Context) (int64, error)
	CountQuestionsByAno(ctx context.Context, ano int32) (int64, error)
	CountQuestionsByAnoAndNivel(ctx context.Context, arg CountQuestionsByAnoAndNivelParams) (int64, error)
	CountQuestionsByAreaAtuacao(ctx context.Context, areaAtuacao pgtype.Text) (int64, error)
	CountQuestionsByAreaFormacao(ctx context.Context, areaFormacao pgtype.Text) (int64, error)
	CountQuestionsByAssunto(ctx context.Context, assuntoID pgtype.UUID) (int64, error)
	CountQuestionsByDificuldadeAndInstituicao(ctx context.Context, arg CountQuestionsByDificuldadeAndInstituicaoParams) (int64, error)
	CountQuestionsByFilters(ctx context.Context, arg CountQuestionsByFiltersParams) (int64, error)
	CountQuestionsByInstituicao(ctx context.Context, instituicao pgtype.Text) (int64, error)
	CountQuestionsByInstituicaoAndCargo(ctx context.Context, arg CountQuestionsByInstituicaoAndCargoParams) (int64, error)
	CountQuestionsByModalidade(ctx context.Context, modalidade pgtype.Text) (int64, error)
	CountQuestionsByNivel(ctx context.Context, nivel pgtype.Text) (int64, error)
	CreateAlternativa(ctx context.Context, arg CreateAlternativaParams) (Alternativa, error)
	CreateAssunto(ctx context.Context, arg CreateAssuntoParams) (Assunto, error)
	CreateDisciplina(ctx context.Context, nome string) (Disciplina, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	DeleteAlternativa(ctx context.Context, id pgtype.UUID) error
	DeleteAssunto(ctx context.Context, id pgtype.UUID) error
	DeleteDisciplina(ctx context.Context, id pgtype.UUID) error
	DeleteQuestion(ctx context.Context, id pgtype.UUID) error
	GetAlternativa(ctx context.Context, id pgtype.UUID) (Alternativa, error)
	GetAssunto(ctx context.Context, id pgtype.UUID) (Assunto, error)
	GetDisciplina(ctx context.Context, id pgtype.UUID) (Disciplina, error)
	GetQuestion(ctx context.Context, id pgtype.UUID) (Question, error)
	ListAlternativasByQuestion(ctx context.Context, questionID pgtype.UUID) ([]Alternativa, error)
	ListAssuntos(ctx context.Context) ([]Assunto, error)
	ListAssuntosByDisciplina(ctx context.Context, disciplinaID pgtype.UUID) ([]Assunto, error)
	ListDisciplinas(ctx context.Context) ([]Disciplina, error)
	ListQuestions(ctx context.Context) ([]Question, error)
	ListQuestionsByAno(ctx context.Context, ano int32) ([]Question, error)
	ListQuestionsByAnoAndNivel(ctx context.Context, arg ListQuestionsByAnoAndNivelParams) ([]Question, error)
	ListQuestionsByAreaAtuacao(ctx context.Context, areaAtuacao pgtype.Text) ([]Question, error)
	ListQuestionsByAreaFormacao(ctx context.Context, areaFormacao pgtype.Text) ([]Question, error)
	ListQuestionsByAssunto(ctx context.Context, assuntoID pgtype.UUID) ([]Question, error)
	ListQuestionsByDificuldadeAndInstituicao(ctx context.Context, arg ListQuestionsByDificuldadeAndInstituicaoParams) ([]Question, error)
	ListQuestionsByFilters(ctx context.Context, arg ListQuestionsByFiltersParams) ([]Question, error)
	ListQuestionsByInstituicao(ctx context.Context, instituicao pgtype.Text) ([]Question, error)
	ListQuestionsByInstituicaoAndCargo(ctx context.Context, arg ListQuestionsByInstituicaoAndCargoParams) ([]Question, error)
	ListQuestionsByModalidade(ctx context.Context, modalidade pgtype.Text) ([]Question, error)
	ListQuestionsByNivel(ctx context.Context, nivel pgtype.Text) ([]Question, error)
	UpdateAlternativa(ctx context.Context, arg UpdateAlternativaParams) (Alternativa, error)
	UpdateAssunto(ctx context.Context, arg UpdateAssuntoParams) (Assunto, error)
	UpdateDisciplina(ctx context.Context, arg UpdateDisciplinaParams) (Disciplina, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
}

var _ Querier = (*Queries)(nil)
