// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountQuestions(ctx context.Context) (int64, error)
	CountQuestionsByFieldOfStudy(ctx context.Context, fieldOfStudy pgtype.Text) (int64, error)
	CountQuestionsByFilters(ctx context.Context, arg CountQuestionsByFiltersParams) (int64, error)
	CountQuestionsByLevel(ctx context.Context, level pgtype.Text) (int64, error)
	CountQuestionsByModality(ctx context.Context, modality pgtype.Text) (int64, error)
	CountQuestionsByPracticeArea(ctx context.Context, practiceArea pgtype.Text) (int64, error)
	CountQuestionsByTopic(ctx context.Context, topicID pgtype.UUID) (int64, error)
	CountQuestionsByYear(ctx context.Context, year int32) (int64, error)
	CountQuestionsByYearAndLevel(ctx context.Context, arg CountQuestionsByYearAndLevelParams) (int64, error)
	CountQuestionsForExam(ctx context.Context, arg CountQuestionsForExamParams) (int64, error)
	CountSubjects(ctx context.Context) (int64, error)
	CountSubjectsByName(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CreateChoice(ctx context.Context, arg CreateChoiceParams) (Choice, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateSubject(ctx context.Context, name string) (Subject, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	DeleteChoice(ctx context.Context, id pgtype.UUID) error
	DeleteQuestion(ctx context.Context, id pgtype.UUID) error
	DeleteSubject(ctx context.Context, id pgtype.UUID) error
	DeleteTopic(ctx context.Context, id pgtype.UUID) error
	GetChoice(ctx context.Context, id pgtype.UUID) (Choice, error)
	GetQuestion(ctx context.Context, id pgtype.UUID) (Question, error)
	GetQuestionsForExam(ctx context.Context, arg GetQuestionsForExamParams) ([]GetQuestionsForExamRow, error)
	GetSubject(ctx context.Context, id pgtype.UUID) (Subject, error)
	GetSubjectByName(ctx context.Context, name string) (Subject, error)
	GetTopic(ctx context.Context, id pgtype.UUID) (Topic, error)
	ListChoicesByQuestion(ctx context.Context, questionID pgtype.UUID) ([]Choice, error)
	ListQuestions(ctx context.Context) ([]Question, error)
	ListQuestionsByFieldOfStudy(ctx context.Context, fieldOfStudy pgtype.Text) ([]Question, error)
	ListQuestionsByFilters(ctx context.Context, arg ListQuestionsByFiltersParams) ([]Question, error)
	ListQuestionsByFiltersWithChoices(ctx context.Context, arg ListQuestionsByFiltersWithChoicesParams) ([]ListQuestionsByFiltersWithChoicesRow, error)
	ListQuestionsByLevel(ctx context.Context, level pgtype.Text) ([]Question, error)
	ListQuestionsByModality(ctx context.Context, modality pgtype.Text) ([]Question, error)
	ListQuestionsByPracticeArea(ctx context.Context, practiceArea pgtype.Text) ([]Question, error)
	ListQuestionsByTopic(ctx context.Context, topicID pgtype.UUID) ([]Question, error)
	ListQuestionsByYear(ctx context.Context, year int32) ([]Question, error)
	ListQuestionsByYearAndLevel(ctx context.Context, arg ListQuestionsByYearAndLevelParams) ([]Question, error)
	ListSubjects(ctx context.Context) ([]Subject, error)
	ListSubjectsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Subject, error)
	ListTopics(ctx context.Context) ([]Topic, error)
	ListTopicsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Topic, error)
	QuestionExistsByStatement(ctx context.Context, statement string) (bool, error)
	UpdateChoice(ctx context.Context, arg UpdateChoiceParams) (Choice, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error)
}

var _ Querier = (*Queries)(nil)
