// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subjects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSubjects = `-- name: CountSubjects :one
SELECT COUNT(*) FROM subjects
`

func (q *Queries) CountSubjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubjectsByName = `-- name: CountSubjectsByName :one
SELECT COUNT(*) FROM subjects WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) CountSubjectsByName(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countSubjectsByName, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateSubject(ctx context.Context, name string) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, name)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubject, id)
	return err
}

const getSubject = `-- name: GetSubject :one
SELECT id, name FROM subjects WHERE id = $1
`

func (q *Queries) GetSubject(ctx context.Context, id pgtype.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubject, id)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSubjectByName = `-- name: GetSubjectByName :one
SELECT id, name FROM subjects WHERE name = $1
`

func (q *Queries) GetSubjectByName(ctx context.Context, name string) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByName, name)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, name FROM subjects ORDER BY name
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsByName = `-- name: ListSubjectsByName :many
SELECT id, name
FROM subjects
WHERE
    name ILIKE '%' || $1 || '%'
ORDER BY name
`

func (q *Queries) ListSubjectsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjectsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subject{}
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects SET name = $2 WHERE id = $1 RETURNING id, name
`

type UpdateSubjectParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject, arg.ID, arg.Name)
	var i Subject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
