// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: topics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (subject_id, name) VALUES ($1, $2) RETURNING id, subject_id, name
`

type CreateTopicParams struct {
	SubjectID pgtype.UUID `json:"subject_id"`
	Name      string      `json:"name"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic, arg.SubjectID, arg.Name)
	var i Topic
	err := row.Scan(&i.ID, &i.SubjectID, &i.Name)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getTopic = `-- name: GetTopic :one
SELECT id, subject_id, name FROM topics WHERE id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id pgtype.UUID) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(&i.ID, &i.SubjectID, &i.Name)
	return i, err
}

const listTopics = `-- name: ListTopics :many
SELECT id, subject_id, name FROM topics ORDER BY name
`

func (q *Queries) ListTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(&i.ID, &i.SubjectID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopicsBySubject = `-- name: ListTopicsBySubject :many
SELECT id, subject_id, name FROM topics WHERE subject_id = $1 ORDER BY name
`

func (q *Queries) ListTopicsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopicsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(&i.ID, &i.SubjectID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopic = `-- name: UpdateTopic :one
UPDATE topics
SET
    subject_id = $2,
    name = $3
WHERE
    id = $1 RETURNING id, subject_id, name
`

type UpdateTopicParams struct {
	ID        pgtype.UUID `json:"id"`
	SubjectID pgtype.UUID `json:"subject_id"`
	Name      string      `json:"name"`
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, updateTopic, arg.ID, arg.SubjectID, arg.Name)
	var i Topic
	err := row.Scan(&i.ID, &i.SubjectID, &i.Name)
	return i, err
}
